exports.body     = require('./body')
exports.favicon  = require('./favicon')
exports.logger   = require('./logger')
exports.mim      = require('./mim')
exports.query    = require('./query')
exports.statiq   = require('./static')